FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["TaskProcessor.Worker/TaskProcessor.Worker.csproj", "TaskProcessor.Worker/"]
COPY ["TaskProcessor.Application/TaskProcessor.Application.csproj", "TaskProcessor.Application/"]
COPY ["TaskProcessor.Domain/TaskProcessor.Domain.csproj", "TaskProcessor.Domain/"]
COPY ["TaskProcessor.Infrastructure/TaskProcessor.Infrastructure.csproj", "TaskProcessor.Infrastructure/"]
RUN dotnet restore "TaskProcessor.Worker/TaskProcessor.Worker.csproj"
COPY . .
WORKDIR "/src/TaskProcessor.Worker"
RUN dotnet build "TaskProcessor.Worker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TaskProcessor.Worker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_ENVIRONMENT=Docker
ENTRYPOINT ["dotnet", "TaskProcessor.Worker.dll"]
