FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5034

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["TaskProcessor.API/TaskProcessor.API.csproj", "TaskProcessor.API/"]
COPY ["TaskProcessor.Application/TaskProcessor.Application.csproj", "TaskProcessor.Application/"]
COPY ["TaskProcessor.Domain/TaskProcessor.Domain.csproj", "TaskProcessor.Domain/"]
COPY ["TaskProcessor.Infrastructure/TaskProcessor.Infrastructure.csproj", "TaskProcessor.Infrastructure/"]
RUN dotnet restore "TaskProcessor.API/TaskProcessor.API.csproj"
COPY . .
WORKDIR "/src/TaskProcessor.API"
RUN dotnet build "TaskProcessor.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TaskProcessor.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_ENVIRONMENT=Docker
ENTRYPOINT ["dotnet", "TaskProcessor.API.dll"]
	